import React, { createContext, ReactNode, useContext, useEffect, useState } from 'react';

// Language options
export type Language = 'en' | 'tmz' | 'fr';

type Translations = {
  [key: string]: {
    [key: string]: string;
  };
};

// Default translations - in a real app, these would be loaded from JSON files or API
const translations: Translations = {
  en: {
    'Home': 'Home',
    'Artists': 'Artists',
    'Events': 'Events',
    'Shop': 'Shop',
    'Podcast': 'Podcast',
    'Knowledge': 'Knowledge',
    'Contact': 'Contact',
    'Profile': 'Profile',
    'Favorites': 'Favorites',
    'Settings': 'Settings',
    'Order History': 'Order History',
    'Admin Dashboard': 'Admin Dashboard',
    'Admin': 'Admin',
    'Logout': 'Logout',
    'Login': 'Login',
    'Login / Register': 'Login / Register',
    'Light Mode': 'Light Mode',
    'Dark Mode': 'Dark Mode',
    'Switch to light mode': 'Switch to light mode',
    'Switch to dark mode': 'Switch to dark mode',
    'Close menu': 'Close menu',
    'Open menu': 'Open menu',
    'Shopping Cart': 'Shopping Cart',
    'Your Cart': 'Your Cart',
    'Close Cart': 'Close Cart',
    'Your cart is empty': 'Your cart is empty',
    'Looks like you haven\'t added any products to your cart yet.': 'Looks like you haven\'t added any products to your cart yet.',
    'Browse Products': 'Browse Products',
    'Decrease Quantity': 'Decrease Quantity',
    'Increase Quantity': 'Increase Quantity',
    'Remove Item': 'Remove Item',
    'Subtotal': 'Subtotal',
    'navbar.login': 'Login',
    'Total': 'Total',
    'Clear Cart': 'Clear Cart',
    'Checkout': 'Checkout',
    'Item added to cart': 'Item added to cart',
    'Item quantity updated': 'Item quantity updated',
    'Item removed from cart': 'Item removed from cart',
    'Cart cleared': 'Cart cleared',
    'All items have been removed from your cart': 'All items have been removed from your cart',
    'Quick Links': 'Quick Links',
    'Legal': 'Legal',
    'Contact Us': 'Contact Us',
    'Terms of Service': 'Terms of Service',
    'Privacy Policy': 'Privacy Policy',
    'Cookie Policy': 'Cookie Policy',
    'Shipping Policy': 'Shipping Policy',
    'Refund Policy': 'Refund Policy',
    'All rights reserved.': 'All rights reserved.',
    'Izuran Records is a record label and event promoter that celebrates Amazigh culture, psychedelic electronic music, and esoteric knowledge.': 'Izuran Records is a record label and event promoter that celebrates Amazigh culture, psychedelic electronic music, and esoteric knowledge.',
    // Authentication translations
    'auth.welcome': 'Welcome to Izuran',
    'auth.welcomeDescription': 'Enter your credentials to access your account',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'login.title': 'Sign In',
    'login.subtitle': 'Welcome back to your musical journey',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.or': 'or',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.termsNotice': 'By continuing, you agree to our Terms of Service and Privacy Policy',
    'register.title': 'Create Account',
    'register.subtitle': 'Join the Izuran community today',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.username': 'Username',
    'register.email': 'Email',
    'register.password': 'Password',
    'auth.successTitle': 'Connected successfully',
    'register.confirmPassword': 'Confirm Password',
    'register.submit': 'Create Account',
    'auth.heroDescription': 'Journey through ancient rhythms and future visions with Izuran\'s psychedelic electronic soundscapes',
    'auth.feature1': 'Discover exclusive tracks from emerging electronic artists',
    'auth.feature2': 'Access premium podcast episodes and interviews',
    'auth.feature3': 'Get early access to events and merchandise',
    // Profile translations
    'profile.title': 'User Profile',
    'profile.details': 'Profile Details',
    'profile.viewDescription': 'View and manage your profile details.',
    'profile.editingDescription': 'Edit your profile details.',
    'profile.username': 'Username',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.memberSince': 'Member Since',
    'profile.adminBadge': 'Admin',
    'profile.editProfile': 'Edit Profile',
    'profile.cancelEditing': 'Cancel',
    'profile.saveChanges': 'Save Changes',
    'profile.notProvided': 'Not Provided',
    'profile.loading': 'Loading profile...',
    // Settings translations
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.loading': 'Loading settings...',
    'settings.notifications': 'Notifications',
    'settings.notificationsDescription': 'Manage your notification preferences.',
    'settings.comingSoon': 'Coming Soon!',
    'settings.notificationsComingSoon': 'Notification settings are coming soon. Stay tuned for updates!',
    'settings.dangerZone': 'Danger Zone',
    'settings.dangerZoneDescription': 'Advanced settings for account management.',
    'settings.logout': 'Logout',
    'settings.changePassword': 'Change Password',
    'settings.logoutDescription': 'Log out from your account.',
    'settings.logoutButton': 'Log out',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDescription': 'Permanently delete your account and all associated data.',
    'settings.deleteWarningTitle': 'Are you absolutely sure?',
    'settings.deleteWarningDescription': 'This action cannot be undone. This will permanently delete your account and remove your data from our servers.',
    'settings.cancel': 'Cancel',
    'settings.confirmDelete': 'Yes, delete my account',
    'settings.deleteAccountButton': 'Delete Account',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose your preferred language.',
    'settings.theme': 'Theme',
    'settings.themeDescription': 'Customize the look and feel of the application.',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDescription': 'Enable dark mode for a darker aesthetic.',
    'settings.accountDeletionDisabled': 'Account Deletion Disabled',
    'settings.accountDeletionDisabledDescription': 'Account deletion is currently disabled for this demo. Please contact support if you wish to delete your account.',
    'settings.passwordInfo': 'Update your password here.',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'settings.updatePassword': 'Update Password',
    'settings.googleUserPasswordInfo': 'Password change is disabled for Google-linked accounts. You can only change your password if you set one up directly.',
    'settings.googleUserPasswordHelp': 'If you wish to set a password, please use the \'Forgot Password\' option on the login page after logging out.',
    'settings.passwordChangeSuccess': 'Password Updated',
    'settings.passwordChangeSuccessDesc': 'Your password has been successfully updated.',
    'settings.passwordChangeError': 'Password Change Failed',
    'settings.passwordChangeErrorDesc': 'An error occurred while trying to update your password. Please try again.',
    'settings.updating': 'Updating...',
    'settings.passwordMismatch': 'Passwords do not match',
    'settings.passwordSame': 'New password must be different from current password',
    'settings.passwordMinLength': 'Password must be at least 8 characters',
    'settings.currentPasswordRequired': 'Current password is required',
    'favorites.title': 'Your Favorites',
    'favorites.podcasts': 'Podcasts',
    'favorites.podcastsTitle': 'Favorite Podcasts',
    'favorites.podcastsDescription': 'All your favorite podcasts in one place. Listen again or discover more.',
    'favorites.loading': 'Loading your favorites...',
    'favorites.loadingPodcasts': 'Loading favorite podcasts...',
    'favorites.noPodcasts': 'No favorite podcasts yet',
    'favorites.noPodcastsDescription': 'You haven\'t added any podcasts to your favorites. Explore and add some!',
    'favorites.removeSuccess': 'Removed from favorites',
    'favorites.removeSuccessDescription': 'The podcast was removed from your favorites.',
    'favorites.removeError': 'Could not remove favorite',
    'favorites.removeErrorDescription': 'There was a problem removing this podcast from your favorites.',
    'favorites.artist': 'Artist',
    'favorites.genre': 'Genre',
    'favorites.duration': 'Duration',
    'favorites.listen': 'Listen',
    'favorites.remove': 'Remove',
  },
  tmz: {
    'Home': 'ⵜⴰⵡⵡⵓⵔⵜ',
    'Artists': 'ⵉⵏⴰⵥⵓⵔⵏ',
    'Events': 'ⵉⵎⵢⴰⴳⴰⵡⵏ',
    'Shop': 'ⵜⴰⵃⴰⵏⵓⵜ',
    'Podcast': 'ⵓⵏⵓⴼⵏ',
    'Knowledge': 'ⵜⴰⵎⵓⵙⵙⵏⵉ',
    'Contact': 'ⴰⵏⵏⴰⵢ',
    'Profile': 'ⴰⵎⵍⵉⵀ',
    'Favorites': 'ⵉⵏⵓⵔⵣⴰⵏ',
    'Settings': 'ⵉⵙⵖⴰⵍⵏ',
    'Admin Dashboard': 'ⵜⴰⴼⵍⵡⵉⵜ ⵏ ⵓⵏⵎⵀⴰⵍ',
    'Admin': 'ⴰⵏⵎⵀⴰⵍ',
    'Logout': 'ⴼⴼⵖ',
    'Login': 'ⴽⵛⵎ',
    'Login / Register': 'ⴽⵛⵎ / ⵥⵎⵎⵎ',
    'Light Mode': 'ⴰⵙⴽⴰⵏ ⵉⴷⴳⴳⵯⴰⵔⵏ',
    'Dark Mode': 'ⴰⵙⴽⴰⵏ ⵓⴱⵔⴽⴰⵏ',
    'Switch to light mode': 'ⴱⴷⴷⵍ ⵖⵔ ⵓⵙⴽⴰⵏ ⵉⴷⴳⴳⵯⴰⵔⵏ',
    'Switch to dark mode': 'ⴱⴷⴷⵍ ⵖⵔ ⵓⵙⴽⴰⵏ ⵓⴱⵔⴽⴰⵏ',
    'Close menu': 'ⵔⴳⵍ ⵓⵎⵓⵖ',
    'Open menu': 'ⵕⵥⵎ ⵓⵎⵓⵖ',
    'Shopping Cart': 'ⵜⴰⴽⵔⵔⵓⵙⵜ ⵏ ⵜⵖⵔⵉ',
    'Your Cart': 'ⵜⴰⴽⵔⵔⵓⵙⵜ ⵏⵏⴽ',
    'Close Cart': 'ⵔⴳⵍ ⵜⴰⴽⵔⵔⵓⵙⵜ',
    'Your cart is empty': 'ⵜⴰⴽⵔⵔⵓⵙⵜ ⵏⵏⴽ ⵜⵓⵍⴰ',
    'Looks like you haven\'t added any products to your cart yet.': 'ⵉⴱⴰⵏ ⴷ ⵓⵔ ⵜⵔⵏⵓⴷ ⴽⵔⴰ ⵏ ⵉⴼⵔⵜⴰⵏ ⵉ ⵜⴽⵔⵔⵓⵙⵜ ⵏⵏⴽ ⵙⵓⵍ.',
    'Browse Products': 'ⵎⵙⴽⵍ ⵉⴼⵔⴷⵉⵙⵏ',
    'Decrease Quantity': 'ⵏⵇⵇⵙ ⵜⴰⵏⴳⴰⵎⵜ',
    'Increase Quantity': 'ⵔⵏⵓ ⵜⴰⵏⴳⴰⵎⵜ',
    'Remove Item': 'ⴽⴽⵙ ⴰⴼⵔⴷⵉⵙ',
    'Subtotal': 'ⴰⵙⵉⵎⴹⵢⴰⵏ',
    'Total': 'ⴰⵎⴹⴰⵢⴰⵏ',
    'Clear Cart': 'ⵙⴼⵓⴼⴷ ⵜⴰⴽⵔⵔⵓⵙⵜ',
    'Checkout': 'ⴼⴼⵖ ⵙ ⵡⴰⴷⴰⴼ',
    'Item added to cart': 'ⴰⴼⵔⴷⵉⵙ ⵉⵜⵜⵓⵔⵏⴰ ⵉ ⵜⴽⵔⵔⵓⵙⵜ',
    'Item quantity updated': 'ⵜⴰⵏⴳⴰⵎⵜ ⵏ ⵓⴼⵔⴷⵉⵙ ⵜⵜⵓⵙⵎⴳⴷⴰ',
    'Item removed from cart': 'ⴰⴼⵔⴷⵉⵙ ⵉⵜⵜⵓⴽⴽⵙ ⵙⴳ ⵜⴽⵔⵔⵓⵙⵜ',
    'Cart cleared': 'ⵜⴰⴽⵔⵔⵓⵙⵜ ⵜⵜⵓⵙⴼⵓⴼⴷ',
    'All items have been removed from your cart': 'ⴰⴽⴽ ⵉⴼⵔⴷⵉⵙⵏ ⵜⵜⵓⴽⴽⵙⵏ ⵙⴳ ⵜⴽⵔⵔⵓⵙⵜ ⵏⵏⴽ',
    'Quick Links': 'ⵉⵣⴷⴰⵢⵏ ⵉⵙⵡⵓⵔⴰⵏ',
    'Legal': 'ⴰⵣⵔⴼⴰⵏ',
    'Contact Us': 'ⴰⵏⵏⴰⵢ ⴰⵖ',
    'Terms of Service': 'ⵜⵉⵖⴰⵍ ⵏ ⵜⵏⵓⴱⴳⴰ',
    'Privacy Policy': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⵜⵓⵙⵍⵉⴳⵜ',
    'Cookie Policy': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⵜⴽⵓⴽⵉⵜ',
    'Shipping Policy': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⵓⵛⵉⵡⵍ',
    'Refund Policy': 'ⵜⴰⵙⵔⵜⵉⵜ ⵏ ⵓⵙⵓⵔⵣⵎ',
    'All rights reserved.': 'ⴰⴽⴽ ⵉⵣⵔⴼⴰⵏ ⵜⵜⵓⵖⴰⵍⵏ.',
    'Izuran Records is a record label and event promoter that celebrates Amazigh culture, psychedelic electronic music, and esoteric knowledge.': 'ⵉⵣⵓⵔⴰⵏ ⵉⴳⴰ ⵜⴰⵎⵙⵏⵙⵉⵖⵜ ⵏ ⵓⵣⵏⵏⵥ ⴷ ⵓⵙⴳⴰⵎ ⵏ ⵉⵎⵢⴰⴳⴰⵡⵏ ⵉⴷⴰ ⵉⵜⵜⵣⵍⵓⵍⵍⵓⵢⵏ ⴰⴷⵔⵉⵣ ⴰⵎⴰⵣⵉⵖ, ⴰⵣⵏⵥⴰⵔ ⴰⵎⵙⵍⵉⵍⵉⴽ ⴷ ⵜⵎⵓⵙⵙⵏⵉ ⵜⴰⵔⵜⵓⵍⵜ.',
    // Authentication translations
    'auth.welcome': 'ⴰⵔⵀⴰⴱⴰ ⵙ ⵉⵣⵓⵔⴰⵏ',
    'auth.welcomeDescription': 'ⴰⴷⴼⵔ ⵉⵏⵖⵎⵉⵙⵏ ⵏⵏⴽ ⵃⵎⴰ ⴰⴷ ⵜⴽⵛⵎⴷ ⵖⵔ ⵓⵏⵙⴽⵔ ⵏⵏⴽ',
    'auth.login': 'ⴽⵛⵎ',
    'auth.register': 'ⵣⵎⵎⵎ',
    'login.title': 'ⴽⵛⵎ',
    'login.subtitle': 'ⴰⵔⵀⴰⴱⴰ ⵙ ⵜⵎⴰⵣⵉⵔⵜ ⵏⵏⴽ ⵜⴰⵎⵓⵙⵉⵇⵜ',
    'login.email': 'ⵉⵎⴰⵢⵍ',
    'login.password': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ',
    'login.submit': 'ⴽⵛⵎ',
    'login.or': 'ⵏⵖ',
    'auth.continueWithGoogle': 'ⴽⵎⵎⵍ ⵙ Google',
    'auth.termsNotice': 'ⵙ ⵓⴽⵎⵎⵍ, ⴰⵔ ⵜⵇⴱⵍⴷ ⵉⵖⴰⵡⴰⵙⵏ ⵏⵏⵖ ⴷ ⵜⵙⵔⵜⵉⵜ ⵏ ⵜⵓⵏⵍⵉⵜ',
    'register.title': 'ⵔⵏⵓ ⵓⵏⵙⴽⵔ',
    'register.subtitle': 'ⴷⴷⵓ ⵉ ⵜⵎⴰⴳⵔⴰⵡⵜ ⵏ ⵉⵣⵓⵔⴰⵏ ⴰⵙⵙ ⴰ',
    'register.firstName': 'ⵉⵙⵎ ⴰⵎⵣⵡⴰⵔⵓ',
    'register.lastName': 'ⵉⵙⵎ ⵏ ⵜⴰⵡⵊⴰ',
    'register.username': 'ⵉⵙⵎ ⵏ ⵓⵙⵙⵔⵙ',
    'register.email': 'ⵉⵎⴰⵢⵍ',
    'register.password': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ',
    'register.confirmPassword': 'ⵙⵏⵢ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ',
    'register.submit': 'ⵔⵏⵓ ⵓⵏⵙⴽⵔ',
    'auth.heroDescription': 'ⴰⴷⵔⵉⵣ ⵙ ⵉⵔⵉⵜⵎⵏ ⵉⵣⴰⵢⴽⵓⵜⵏ ⴷ ⵜⴱⵔⵉⴷⵜ ⵏ ⵡⴰⴷⴰⴼ ⵙ ⵜⵓⵏⴳⵉⵏ ⵜⵉⵎⵙⵍⵉⵍⵉⴽⵉⵏ ⵏ ⵉⵣⵓⵔⴰⵏ',
    'auth.feature1': 'ⴰⴼ ⵜⵉⵣⵍⵉⵜⵉⵏ ⵉⵥⵍⵉⵏ ⵙⴳ ⵉⵏⴰⵥⵓⵔⵏ ⵉⵎⴰⵢⵏⵓⵜⵏ',
    'auth.feature2': 'ⴰⴽⴻⵚ ⵉ ⵉⴼⵔⴰⵔⵏ ⵏ ⵓⵏⵓⴼⵏ ⴷ ⵓⵙⵓⵡⵍ',
    'auth.feature3': 'ⴰⵡⵉ ⴰⴽⴻⵚ ⴰⵣⵡⴰⵔ ⵉ ⵉⵎⵢⴰⴳⴰⵡⵏ ⴷ ⵜⵖⵔⵉⵜⵉⵏ',
    // Profile translations
    'profile.title': 'ⴰⵎⵍⵉⵀ ⵏ ⵓⵙⵙⵔⵙ',
    'profile.details': 'ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵓⵎⵍⵉⵀ',
    'profile.viewDescription': 'ⵥⵕ ⴷ ⵙⵎⵓⵜⵜⴳ ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵓⵎⵍⵉⵀ ⵏⵏⴽ.',
    'profile.editingDescription': 'ⵙⵎⵓⵜⵜⴳ ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵓⵎⵍⵉⵀ ⵏⵏⴽ.',
    'profile.username': 'ⵉⵙⵎ ⵏ ⵓⵙⵙⵔⵙ',
    'profile.firstName': 'ⵉⵙⵎ ⴰⵎⵣⵡⴰⵔⵓ',
    'profile.lastName': 'ⵉⵙⵎ ⵏ ⵜⴰⵡⵊⴰ',
    'profile.email': 'ⵉⵎⴰⵢⵍ',
    'profile.memberSince': 'ⴰⵎⴷⵔⴰⵡ ⵙⴳ',
    'profile.adminBadge': 'ⴰⵏⵎⵀⴰⵍ',
    'profile.editProfile': 'ⵙⵎⵓⵜⵜⴳ ⴰⵎⵍⵉⵀ',
    'profile.cancelEditing': 'ⵙⵔⵙ',
    'profile.saveChanges': 'ⵃⴼⴹ ⵉⴱⴷⴷⴰⴷⵏ',
    'profile.notProvided': 'ⵓⵔ ⵉⵜⵜⵓⴼⴽⴰ ⵖ',
    'profile.loading': 'ⴰⵎⵍⵉⵀ ⴰⵔ ⵉⵜⵜⵡⴰⵙⵙⴰⵔ...',
    // Settings translations
    'settings.title': 'ⵉⵙⵖⴰⵍⵏ',
    'settings.account': 'ⴰⵏⵙⴽⵔ',
    'settings.appearance': 'ⴰⵙⴽⴰⵏ',
    'settings.loading': 'ⵉⵙⵖⴰⵍⵏ ⴰⵔ ⵜⵜⵡⴰⵙⵙⴰⵔⵏ...',
    'settings.notifications': 'ⵉⵍⵖⴰⵎⵏ',
    'settings.notificationsDescription': 'ⵙⵎⵓⵜⵜⴳ ⵉⵙⵖⴰⵍⵏ ⵏ ⵉⵍⵖⴰⵎⵏ ⵏⵏⴽ.',
    'settings.comingSoon': 'ⴰⵔ ⴷ ⵉⵜⵜⴰⴷⴷⴰ!',
    'settings.notificationsComingSoon': 'ⵉⵙⵖⴰⵍⵏ ⵏ ⵉⵍⵖⴰⵎⵏ ⴰⵔ ⴷ ⵜⵜⴰⴷⴷⴰⵏ. ⵜⵉⵍⵉ ⵉⵡⴰⵏ!',
    'settings.dangerZone': 'ⴰⵎⵏⵉⴷ ⵏ ⵡⴰⵔⴰⵢ',
    'settings.dangerZoneDescription': 'ⵉⵙⵖⴰⵍⵏ ⵉⵎⴰⵢⵏⵓⵜⵏ ⵏ ⵓⵙⵎⵓⵜⵜⴳ ⵏ ⵓⵏⵙⴽⵔ.',
    'settings.logout': 'ⴼⴼⵖ',
    'settings.logoutDescription': 'ⴼⴼⵖ ⵙⴳ ⵓⵏⵙⴽⵔ ⵏⵏⴽ.',
    'settings.logoutButton': 'ⴼⴼⵖ',
    'settings.deleteAccount': 'ⴽⴽⵙ ⴰⵏⵙⴽⵔ',
    'settings.deleteAccountDescription': 'ⴽⴽⵙ ⴰⵏⵙⴽⵔ ⵏⵏⴽ ⴷ ⴰⴽⴽ ⵉⵏⵖⵎⵉⵙⵏ ⵉⵎⵓⵏⵏ ⵏⵏⵙ.',
    'settings.deleteWarningTitle': 'ⵉⵡⵉ ⵙⵏⵜⵎ ⵜⵜⴳⴰⵎ?',
    'settings.deleteWarningDescription': 'ⴰⵡⴰⵍ ⴰ ⵓⵔ ⵉⵣⵎⵎⵓⵎⵓ ⴰⴷ ⵉⵜⵜⵡⴰⵙⵙⵏⵜ. ⴰⵡⴰⵍ ⴰ ⴰⵔ ⵉⴽⴽⵙ ⴰⵏⵙⴽⵔ ⵏⵏⴽ ⴷ ⴰⴽⴽ ⵉⵏⵖⵎⵉⵙⵏ ⵏⵏⴽ ⵙⴳ ⵉⵎⵉⴽⵏ ⵏⵏⵖ.',
    'settings.cancel': 'ⵙⵔⵙ',
    'settings.confirmDelete': 'ⴰⵢⵢⵉ, ⴽⴽⵙ ⴰⵏⵙⴽⵔ ⵉⵏⵓ',
    'settings.deleteAccountButton': 'ⴽⴽⵙ ⴰⵏⵙⴽⵔ',
    'settings.language': 'ⵜⵓⵜⵍⴰⵢⵜ',
    'settings.languageDescription': 'ⴰⵔⴰ ⵜⵓⵜⵍⴰⵢⵜ ⵜⴰⵔⴰⴱⴱⴰ.',
    'settings.theme': 'ⴰⵙⴽⴰⵏ',
    'settings.themeDescription': 'ⵙⵎⵓⵜⵜⴳ ⴰⵙⴽⴰⵏ ⴷ ⵓⵎⴷⵔⴰⵡ ⵏ ⵜⵙⵏⵓⵔⴰ.',
    'settings.darkMode': 'ⴰⵙⴽⴰⵏ ⵓⴱⵔⴽⴰⵏ',
    'settings.darkModeDescription': 'ⴰⵙⴽⴰⵏ ⵓⴱⵔⴽⴰⵏ ⵉ ⵓⵙⴽⴰⵏ ⴰⴱⵔⴽⴰⵏ.',
    'settings.accountDeletionDisabled': 'ⴰⵙⵏⵓⵏⵜ ⵏ ⵓⵏⵙⴽⵔ ⵉⵜⵜⵓⵙⵔⵙ',
    'settings.accountDeletionDisabledDescription': 'ⴰⵙⵏⵓⵏⵜ ⵏ ⵓⵏⵙⴽⵔ ⵉⵜⵜⵓⵙⵔⵙ ⵖ ⵓⵙⴽⴰⵏ ⴰ. ⴰⵔ ⵜⵜⵉⵏⵉⴷ ⴰⵙⵏⵓⵏⵜ ⵏⵏⵖ ⵉⴼ ⵜⵔⵉⴷ ⴰⴷ ⵜⵙⵏⵓⵏⵜ ⴰⵏⵙⴽⵔ ⵏⵏⴽ.',
    'settings.passwordInfo': 'ⵙⵎⵓⵜⵜⴳ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵏⵏⴽ.',
    'settings.currentPassword': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⴰⵎⴰⵢⵏⵓ',
    'settings.newPassword': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⴰⵎⴰⵢⵏⵓ',
    'settings.confirmNewPassword': 'ⵙⵏⵢ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⴰⵎⴰⵢⵏⵓ',
    'settings.updatePassword': 'ⵙⵎⵓⵜⵜⴳ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ',
    'settings.googleUserPasswordInfo': 'ⴰⵙⵏⵓⵏⵜ ⵏ ⵓⵙⵎⵓⵜⵜⴳ ⵏ ⵡⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵉⵜⵜⵓⵙⵔⵙ ⵉ ⵉⵙⴽⵔⵏ ⵉⵎⵓⵏⵏ ⵙ Google. ⴰⵔ ⵜⵣⵎⵎⴰⵔⴷ ⴰⴷ ⵜⵙⵏⵓⵏⵜ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵏⵏⴽ ⵉⴼ ⵜⵣⵎⵎⴰⵔⴷ ⴰⴷ ⵜⵙⵏⵓⵏⵜ ⵢⴰⵏ ⵙ ⵓⵙⴰⵜⵉ ⵓⴼⵔⵉⵙ.',
    'settings.googleUserPasswordHelp': 'ⵉⴼ ⵜⵔⵉⴷ ⴰⴷ ⵜⵙⵏⵓⵏⵜ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ, ⴰⵔⴰ ⵜⴰⵙⵖⴰⵍⵜ \'ⵜⵜⵓⵖ ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ\' ⵖ ⵜⴰⵙⵏⴰ ⵏ ⵓⴽⵛⵎ ⵏ ⵓⵏⵙⴽⵔ ⵏⵏⴽ ⵙⴳ ⵓⵙⴳⴳⵔ.',
    'settings.passwordChangeSuccess': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵉⵜⵜⵓⵙⵎⴳⴷⴰ',
    'settings.passwordChangeSuccessDesc': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵏⵏⴽ ⵉⵜⵜⵓⵙⵎⴳⴷⴰ ⵙ ⵓⵎⴰⵜⵜⴰⵢ.',
    'settings.passwordChangeError': 'ⴰⵙⵏⵓⵏⵜ ⵏ ⵡⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵓⵔ ⵉⵣⵔⵉ',
    'settings.passwordChangeErrorDesc': 'ⵉⵎⴰⵏ ⴽⵔⴰ ⵏ ⵓⵙⵏⵓⵏⵜ ⵖ ⵓⵙⵎⵓⵜⵜⴳ ⵏ ⵡⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵏⵏⴽ. ⵎⵍⴰ ⵜⴰⵙⵏⵓⵏⵜ ⴷⴼⴼⵉⵔ ⵓⴷⵔⵉⵙ.',
    'settings.updating': 'ⴰⵔ ⵉⵜⵜⵓⵙⵎⴳⴷⴰ...',
    'settings.passwordMismatch': 'ⵉⵔⴰⵣⵏ ⵏ ⵡⵓⴼⴼⵉⵔ ⵓⵔ ⵎⵢⴰⵡⴰⴹⵏ',
    'settings.passwordSame': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⴰⵎⴰⵢⵏⵓ ⵉⵅⵚⵚⴰ ⴰⴷ ⵉⴳ ⵎⵛⵜⴰ ⵙⴳ ⵡⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⴰⵎⴰⵢⵏⵓ',
    'settings.passwordMinLength': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⵉⵅⵚⵚⴰ ⴰⴷ ⵉⴳ ⴰⵔ ⵜⴰⵎⴹⵍⴰⵜ 8 ⵉⵙⴽⴽⵉⵍⵏ',
    'settings.currentPasswordRequired': 'ⴰⵔⴰⵣ ⵓⴼⴼⵉⵔ ⴰⵎⴰⵢⵏⵓ ⵉⵅⵚⵚⴰ ⴰⴷ ⵉⴳ ⵉⵏⵓⵔⵣ',
    'favorites.title': 'Your Favorites',
    'favorites.podcasts': 'Podcasts',
    'favorites.podcastsTitle': 'Favorite Podcasts',
    'favorites.podcastsDescription': 'All your favorite podcasts in one place. Listen again or discover more.',
    'favorites.loading': 'Loading your favorites...',
    'favorites.loadingPodcasts': 'Loading favorite podcasts...',
    'favorites.noPodcasts': 'No favorite podcasts yet',
    'favorites.noPodcastsDescription': 'You haven\'t added any podcasts to your favorites. Explore and add some!',
    'favorites.removeSuccess': 'Removed from favorites',
    'favorites.removeSuccessDescription': 'The podcast was removed from your favorites.',
    'favorites.removeError': 'Could not remove favorite',
    'favorites.removeErrorDescription': 'There was a problem removing this podcast from your favorites.',
    'favorites.artist': 'Artist',
    'favorites.genre': 'Genre',
    'favorites.duration': 'Duration',
    'favorites.listen': 'Listen',
    'favorites.remove': 'Remove',
  },
  fr: {
    'Home': 'Accueil',
    'Artists': 'Artistes',
    'Events': 'Événements',
    'Shop': 'Boutique',
    'Podcast': 'Podcast',
    'Knowledge': 'Connaissance',
    'Contact': 'Contact',
    'Profile': 'Profil',
    'Favorites': 'Favoris',
    'Settings': 'Paramètres',
    'Order History': 'Historique des commandes',
    'Admin Dashboard': 'Tableau de bord administrateur',
    'Admin': 'Admin',
    'Logout': 'Déconnexion',
    'Login': 'Connexion',
    'Login / Register': 'Connexion / Inscription',
    'Light Mode': 'Mode clair',
    'Dark Mode': 'Mode sombre',
    'Switch to light mode': 'Passer en mode clair',
    'Switch to dark mode': 'Passer en mode sombre',
    'Close menu': 'Fermer le menu',
    'Open menu': 'Ouvrir le menu',
    'Shopping Cart': 'Panier',
    'Your Cart': 'Votre panier',
    'Close Cart': 'Fermer le panier',
    'Your cart is empty': 'Votre panier est vide',
    'Looks like you haven\'t added any products to your cart yet.': 'Il semble que vous n\'avez pas encore ajouté de produits à votre panier.',
    'Browse Products': 'Parcourir les produits',
    'Decrease Quantity': 'Diminuer la quantité',
    'Increase Quantity': 'Augmenter la quantité',
    'Remove Item': 'Supprimer l\'article',
    'Subtotal': 'Sous-total',
    'Total': 'Total',
    'Clear Cart': 'Vider le panier',
    'Checkout': 'Paiement',
    'Item added to cart': 'Article ajouté au panier',
    'Item quantity updated': 'Quantité de l\'article mise à jour',
    'Item removed from cart': 'Article retiré du panier',
    'Cart cleared': 'Panier vidé',
    'All items have been removed from your cart': 'Tous les articles ont été retirés de votre panier',
    'Quick Links': 'Liens rapides',
    'Legal': 'Mentions légales',
    'Contact Us': 'Nous contacter',
    'Terms of Service': 'Conditions d\'utilisation',
    'Privacy Policy': 'Politique de confidentialité',
    'Cookie Policy': 'Politique de cookies',
    'Shipping Policy': 'Politique d\'expédition',
    'Refund Policy': 'Politique de remboursement',
    'All rights reserved.': 'Tous droits réservés.',
    'Izuran Records is a record label and event promoter that celebrates Amazigh culture, psychedelic electronic music, and esoteric knowledge.': 'Izuran Records est un label de musique et un promoteur d\'événements qui célèbre la culture amazighe, la musique électronique psychédélique et le savoir ésotérique.',
    // Authentication translations
    'auth.welcome': 'Bienvenue chez Izuran',
    'auth.welcomeDescription': 'Entrez vos identifiants pour accéder à votre compte',
    'auth.login': 'Connexion',
    'auth.register': 'S\'inscrire',
    'login.title': 'Se connecter',
    'login.subtitle': 'Bienvenue de retour dans votre voyage musical',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.submit': 'Se connecter',
    'login.or': 'ou',
    'auth.continueWithGoogle': 'Continuer avec Google',
    'auth.termsNotice': 'En continuant, vous acceptez nos Conditions d\'utilisation et notre Politique de confidentialité',
    'register.title': 'Créer un compte',
    'register.subtitle': 'Rejoignez la communauté Izuran dès aujourd\'hui',
    'register.firstName': 'Prénom',
    'register.lastName': 'Nom',
    'register.username': 'Nom d\'utilisateur',
    'register.email': 'Email',
    'register.password': 'Mot de passe',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.submit': 'Créer un compte',
    'auth.heroDescription': 'Voyagez à travers les rythmes anciens et les visions futures avec les paysages sonores électroniques psychédéliques d\'Izuran',
    'auth.feature1': 'Découvrez des titres exclusifs d\'artistes électroniques émergents',
    'auth.feature2': 'Accédez à des épisodes de podcast et des interviews premium',
    'auth.feature3': 'Obtenez un accès anticipé aux événements et aux produits dérivés',
    // Profile translations
    'profile.title': 'Profil utilisateur',
    'profile.details': 'Détails du profil',
    'profile.viewDescription': 'Afficher et gérer les détails de votre profil.',
    'profile.editingDescription': 'Modifier les détails de votre profil.',
    'profile.username': 'Nom d\'utilisateur',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom de famille',
    'profile.email': 'Email',
    'profile.memberSince': 'Membre depuis',
    'profile.adminBadge': 'Admin',
    'profile.editProfile': 'Modifier le profil',
    'profile.cancelEditing': 'Annuler',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.notProvided': 'Non fourni',
    'profile.loading': 'Chargement du profil...',
    // Settings translations
    'settings.title': 'Paramètres',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.loading': 'Chargement des paramètres...',
    'settings.notifications': 'Notifications',
    'settings.notificationsDescription': 'Gérer vos préférences de notification.',
    'settings.comingSoon': 'Bientôt disponible !',
    'settings.notificationsComingSoon': 'Les paramètres de notification seront bientôt disponibles. Restez à l\'écoute pour les mises à jour !',
    'settings.dangerZone': 'Zone de danger',
    'settings.dangerZoneDescription': 'Paramètres avancés pour la gestion du compte.',
    'settings.logout': 'Déconnexion',
    'settings.logoutDescription': 'Se déconnecter de votre compte.',
    'settings.logoutButton': 'Se déconnecter',
    'settings.deleteAccount': 'Supprimer le compte',
    'settings.deleteAccountDescription': 'Supprimer définitivement votre compte et toutes les données associées.',
    'settings.deleteWarningTitle': 'Êtes-vous absolument sûr ?',
    'settings.deleteWarningDescription': 'Cette action est irréversible. Votre compte et toutes vos données seront supprimés de façon permanente de nos serveurs.',
    'settings.cancel': 'Annuler',
    'settings.confirmDelete': 'Oui, supprimer mon compte',
    'settings.deleteAccountButton': 'Supprimer le compte',
    'settings.language': 'Langue',
    'settings.languageDescription': 'Choisissez votre langue préférée.',
    'settings.theme': 'Thème',
    'settings.themeDescription': 'Personnalisez l\'apparence de l\'application.',
    'settings.darkMode': 'Mode sombre',
    'settings.darkModeDescription': 'Activer le mode sombre pour une esthétique plus sombre.',
    'settings.accountDeletionDisabled': 'Suppression de compte désactivée',
    'settings.accountDeletionDisabledDescription': 'La suppression de compte est actuellement désactivée pour cette démo. Veuillez contacter le support si vous souhaitez supprimer votre compte.',
    'settings.passwordInfo': 'Mettez à jour votre mot de passe ici.',
    'settings.currentPassword': 'Mot de passe actuel',
    'settings.newPassword': 'Nouveau mot de passe',
    'settings.confirmNewPassword': 'Confirmer le nouveau mot de passe',
    'settings.updatePassword': 'Mettre à jour le mot de passe',
    'settings.googleUserPasswordInfo': 'Le changement de mot de passe est désactivé pour les comptes liés à Google. Vous ne pouvez modifier votre mot de passe que si vous en avez configuré un directement.',
    'settings.googleUserPasswordHelp': 'Si vous souhaitez définir un mot de passe, veuillez utiliser l\'option \'Mot de passe oublié\' sur la page de connexion après vous être déconnecté.',
    'settings.passwordChangeSuccess': 'Mot de passe mis à jour',
    'settings.passwordChangeSuccessDesc': 'Votre mot de passe a été mis à jour avec succès.',
    'settings.passwordChangeError': 'Échec du changement de mot de passe',
    'settings.passwordChangeErrorDesc': 'Une erreur est survenue lors de la tentative de mise à jour de votre mot de passe. Veuillez réessayer.',
    'settings.updating': 'Mise à jour...',
    'settings.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'settings.passwordSame': 'Le nouveau mot de passe doit être différent de l\'ancien mot de passe',
    'settings.passwordMinLength': 'Le mot de passe doit contenir au moins 8 caractères',
    'settings.currentPasswordRequired': 'Le mot de passe actuel est requis',
    'favorites.title': 'Your Favorites',
    'favorites.podcasts': 'Podcasts',
    'favorites.podcastsTitle': 'Favorite Podcasts',
    'favorites.podcastsDescription': 'All your favorite podcasts in one place. Listen again or discover more.',
    'favorites.loading': 'Loading your favorites...',
    'favorites.loadingPodcasts': 'Loading favorite podcasts...',
    'favorites.noPodcasts': 'No favorite podcasts yet',
    'favorites.noPodcastsDescription': 'You haven\'t added any podcasts to your favorites. Explore and add some!',
    'favorites.removeSuccess': 'Removed from favorites',
    'favorites.removeSuccessDescription': 'The podcast was removed from your favorites.',
    'favorites.removeError': 'Could not remove favorite',
    'favorites.removeErrorDescription': 'There was a problem removing this podcast from your favorites.',
    'favorites.artist': 'Artist',
    'favorites.genre': 'Genre',
    'favorites.duration': 'Duration',
    'favorites.listen': 'Listen',
    'favorites.remove': 'Remove',
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key; // Fallback to key if translation not found
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}